### ISSUE TITLE
Export with hex filename?

### ISSUE THREAD

**Issue by kilgore-trout-graphics** [jedi661/UoFiddlerPixel#1]
Would it be possible to add an option to export the gump files with their hex filenames instead of decimal?

**Comment by jedi661** [comment]
Is it something specific that you mean and in what context? Otherwise, contact me on Discord. ( jedi66 )..

**Comment by jedi661** [comment]
Added an export function in Gump for all addresses to a text file in decimal or hexadecimal format. 
  Also added an import function to import from a text file and directory with decimal or hexadecimal image names to the specified address.

**Comment by kilgore-trout-graphics** [comment]
@jedi661 Thank you!
